bundle exec ruby bin/authz.rb -p livedplaces -e -s 51
bundle exec ruby bin/authz.rb -p livedplaces -e -s 598
bundle exec ruby bin/authz.rb -p livedplaces -e -s 258
bundle exec ruby bin/authz.rb -p livedplaces -e -s 1003
bundle exec ruby bin/authz.rb -p livedplaces -e -s 2083
bundle exec ruby bin/authz.rb -p livedplaces -e -s 267
bundle exec ruby bin/authz.rb -p livedplaces -e -s 277
bundle exec ruby bin/authz.rb -p livedplaces -e -s 690
bundle exec ruby bin/authz.rb -p livedplaces -e -s 853
bundle exec ruby bin/authz.rb -p livedplaces -e -s 501
bundle exec ruby bin/authz.rb -p livedplaces -e -s 284
bundle exec ruby bin/authz.rb -p livedplaces -e -s 682
bundle exec ruby bin/authz.rb -p livedplaces -e -s 700
bundle exec ruby bin/authz.rb -p livedplaces -e -s 303
bundle exec ruby bin/authz.rb -p livedplaces -e -s 217
bundle exec ruby bin/authz.rb -p livedplaces -e -s 1232
bundle exec ruby bin/authz.rb -p livedplaces -e -s 1739
bundle exec ruby bin/authz.rb -p livedplaces -e -s 315
bundle exec ruby bin/authz.rb -p livedplaces -e -s 59
bundle exec ruby bin/authz.rb -p livedplaces -e -s 967
bundle exec ruby bin/authz.rb -p livedplaces -e -s 321
bundle exec ruby bin/authz.rb -p livedplaces -e -s 1830
bundle exec ruby bin/authz.rb -p livedplaces -e -s 770
bundle exec ruby bin/authz.rb -p livedplaces -e -s 814
bundle exec ruby bin/authz.rb -p livedplaces -e -s 771
bundle exec ruby bin/authz.rb -p livedplaces -e -s 769
bundle exec ruby bin/authz.rb -p livedplaces -e -s 768
bundle exec ruby bin/authz.rb -p livedplaces -e -s 60
bundle exec ruby bin/authz.rb -p livedplaces -e -s 575
bundle exec ruby bin/authz.rb -p livedplaces -e -s 2199
bundle exec ruby bin/authz.rb -p livedplaces -e -s 514
bundle exec ruby bin/authz.rb -p livedplaces -e -s 554
bundle exec ruby bin/authz.rb -p livedplaces -e -s 518
bundle exec ruby bin/authz.rb -p livedplaces -e -s 583
bundle exec ruby bin/authz.rb -p livedplaces -e -s 368
bundle exec ruby bin/authz.rb -p livedplaces -e -s 1891
bundle exec ruby bin/authz.rb -p livedplaces -e -s 1888
bundle exec ruby bin/authz.rb -p livedplaces -e -s 1677
bundle exec ruby bin/authz.rb -p livedplaces -e -s 162
bundle exec ruby bin/authz.rb -p livedplaces -e -s 1
bundle exec ruby bin/authz.rb -p livedplaces -e -s 2
bundle exec ruby bin/authz.rb -p livedplaces -e -s 3
bundle exec ruby bin/authz.rb -p livedplaces -e -s 787
bundle exec ruby bin/authz.rb -p livedplaces -e -s 12
bundle exec ruby bin/authz.rb -p livedplaces -e -s 1676
bundle exec ruby bin/authz.rb -p livedplaces -e -s 1091
bundle exec ruby bin/authz.rb -p livedplaces -e -s 909
bundle exec ruby bin/authz.rb -p livedplaces -e -s 1513
bundle exec ruby bin/authz.rb -p livedplaces -e -s 54
bundle exec ruby bin/authz.rb -p livedplaces -e -s 6
bundle exec ruby bin/authz.rb -p livedplaces -e -s 148
bundle exec ruby bin/authz.rb -p livedplaces -e -s 50
bundle exec ruby bin/authz.rb -p livedplaces -e -s 952
bundle exec ruby bin/authz.rb -p livedplaces -e -s 14
