bundle exec ruby bin/authz.rb -e -p heb -s 1867
bundle exec ruby bin/authz.rb -e -p heb -s 1667
bundle exec ruby bin/authz.rb -e -p heb -s 230
bundle exec ruby bin/authz.rb -e -p heb -s 1482
bundle exec ruby bin/authz.rb -e -p heb -s 1559
bundle exec ruby bin/authz.rb -e -p heb -s 1306
bundle exec ruby bin/authz.rb -e -p heb -s 1560
bundle exec ruby bin/authz.rb -e -p heb -s 874
bundle exec ruby bin/authz.rb -e -p heb -s 1108
bundle exec ruby bin/authz.rb -e -p heb -s 2036
bundle exec ruby bin/authz.rb -e -p heb -s 745
bundle exec ruby bin/authz.rb -e -p heb -s 1564
bundle exec ruby bin/authz.rb -e -p heb -s 1973
bundle exec ruby bin/authz.rb -e -p heb -s 1523
bundle exec ruby bin/authz.rb -e -p heb -s 1851
bundle exec ruby bin/authz.rb -e -p heb -s 1970
bundle exec ruby bin/authz.rb -e -p heb -s 2226
bundle exec ruby bin/authz.rb -e -p heb -s 2227
bundle exec ruby bin/authz.rb -e -p heb -s 1811
bundle exec ruby bin/authz.rb -e -p heb -s 1377
bundle exec ruby bin/authz.rb -e -p heb -s 1766
bundle exec ruby bin/authz.rb -e -p heb -s 327
bundle exec ruby bin/authz.rb -e -p heb -s 2151
bundle exec ruby bin/authz.rb -e -p heb -s 2202
bundle exec ruby bin/authz.rb -e -p heb -s 1224
bundle exec ruby bin/authz.rb -e -p heb -s 1452
bundle exec ruby bin/authz.rb -e -p heb -s 2073
bundle exec ruby bin/authz.rb -e -p heb -s 1709
bundle exec ruby bin/authz.rb -e -p heb -s 1128
bundle exec ruby bin/authz.rb -e -p heb -s 1692
bundle exec ruby bin/authz.rb -e -p heb -s 860
bundle exec ruby bin/authz.rb -e -p heb -s 1770
bundle exec ruby bin/authz.rb -e -p heb -s 2140
bundle exec ruby bin/authz.rb -e -p heb -s 1024
bundle exec ruby bin/authz.rb -e -p heb -s 846
bundle exec ruby bin/authz.rb -e -p heb -s 1842
bundle exec ruby bin/authz.rb -e -p heb -s 1017
bundle exec ruby bin/authz.rb -e -p heb -s 2200
bundle exec ruby bin/authz.rb -e -p heb -s 1326
bundle exec ruby bin/authz.rb -e -p heb -s 1993
bundle exec ruby bin/authz.rb -e -p heb -s 1852
bundle exec ruby bin/authz.rb -e -p heb -s 957
bundle exec ruby bin/authz.rb -e -p heb -s 779
bundle exec ruby bin/authz.rb -e -p heb -s 1330
bundle exec ruby bin/authz.rb -e -p heb -s 850
bundle exec ruby bin/authz.rb -e -p heb -s 580
bundle exec ruby bin/authz.rb -e -p heb -s 2118
bundle exec ruby bin/authz.rb -e -p heb -s 811
bundle exec ruby bin/authz.rb -e -p heb -s 1131
bundle exec ruby bin/authz.rb -e -p heb -s 1835
bundle exec ruby bin/authz.rb -e -p heb -s 2057
bundle exec ruby bin/authz.rb -e -p heb -s 1968
bundle exec ruby bin/authz.rb -e -p heb -s 804
bundle exec ruby bin/authz.rb -e -p heb -s 2040
bundle exec ruby bin/authz.rb -e -p heb -s 1209
bundle exec ruby bin/authz.rb -e -p heb -s 1221
bundle exec ruby bin/authz.rb -e -p heb -s 2012
bundle exec ruby bin/authz.rb -e -p heb -s 1650
bundle exec ruby bin/authz.rb -e -p heb -s 1635
bundle exec ruby bin/authz.rb -e -p heb -s 2272
bundle exec ruby bin/authz.rb -e -p heb -s 1211
bundle exec ruby bin/authz.rb -e -p heb -s 2312
bundle exec ruby bin/authz.rb -e -p heb -s 2138
bundle exec ruby bin/authz.rb -e -p heb -s 782
bundle exec ruby bin/authz.rb -e -p heb -s 1869
bundle exec ruby bin/authz.rb -e -p heb -s 2257
bundle exec ruby bin/authz.rb -e -p heb -s 1906
bundle exec ruby bin/authz.rb -e -p heb -s 2319
bundle exec ruby bin/authz.rb -e -p heb -s 2279
bundle exec ruby bin/authz.rb -e -p heb -s 2127
bundle exec ruby bin/authz.rb -e -p heb -s 2259
bundle exec ruby bin/authz.rb -e -p heb -s 2371
bundle exec ruby bin/authz.rb -e -p heb -s 1122
bundle exec ruby bin/authz.rb -e -p heb -s 1212
bundle exec ruby bin/authz.rb -e -p heb -s 2068
bundle exec ruby bin/authz.rb -e -p heb -s 1793
bundle exec ruby bin/authz.rb -e -p heb -s 1673
bundle exec ruby bin/authz.rb -e -p heb -s 2318
bundle exec ruby bin/authz.rb -e -p heb -s 259
bundle exec ruby bin/authz.rb -e -p heb -s 2349
bundle exec ruby bin/authz.rb -e -p heb -s 1971
bundle exec ruby bin/authz.rb -e -p heb -s 1722
bundle exec ruby bin/authz.rb -e -p heb -s 2256
bundle exec ruby bin/authz.rb -e -p heb -s 2363
bundle exec ruby bin/authz.rb -e -p heb -s 2013
bundle exec ruby bin/authz.rb -e -p heb -s 1963
bundle exec ruby bin/authz.rb -e -p heb -s 1361
bundle exec ruby bin/authz.rb -e -p heb -s 2358
bundle exec ruby bin/authz.rb -e -p heb -s 1378
bundle exec ruby bin/authz.rb -e -p heb -s 2373
bundle exec ruby bin/authz.rb -e -p heb -s 2370
bundle exec ruby bin/authz.rb -e -p heb -s 2372
bundle exec ruby bin/authz.rb -e -p heb -s 2258
bundle exec ruby bin/authz.rb -e -p heb -s 1119
bundle exec ruby bin/authz.rb -e -p heb -s 2352
bundle exec ruby bin/authz.rb -e -p heb -s 1508
bundle exec ruby bin/authz.rb -e -p heb -s 767
bundle exec ruby bin/authz.rb -e -p heb -s 2157
bundle exec ruby bin/authz.rb -e -p heb -s 2315
bundle exec ruby bin/authz.rb -e -p heb -s 2095
bundle exec ruby bin/authz.rb -e -p heb -s 590
bundle exec ruby bin/authz.rb -e -p heb -s 2242
bundle exec ruby bin/authz.rb -e -p heb -s 2193
bundle exec ruby bin/authz.rb -e -p heb -s 1129
bundle exec ruby bin/authz.rb -e -p heb -s 2280
bundle exec ruby bin/authz.rb -e -p heb -s 1107
bundle exec ruby bin/authz.rb -e -p heb -s 2076
bundle exec ruby bin/authz.rb -e -p heb -s 2058
bundle exec ruby bin/authz.rb -e -p heb -s 541
bundle exec ruby bin/authz.rb -e -p heb -s 2333
bundle exec ruby bin/authz.rb -e -p heb -s 1517
bundle exec ruby bin/authz.rb -e -p heb -s 2300
bundle exec ruby bin/authz.rb -e -p heb -s 2244
bundle exec ruby bin/authz.rb -e -p heb -s 1102
bundle exec ruby bin/authz.rb -e -p heb -s 816
bundle exec ruby bin/authz.rb -e -p heb -s 2305
bundle exec ruby bin/authz.rb -e -p heb -s 1592
bundle exec ruby bin/authz.rb -e -p heb -s 1130
bundle exec ruby bin/authz.rb -e -p heb -s 2343
bundle exec ruby bin/authz.rb -e -p heb -s 2348
bundle exec ruby bin/authz.rb -e -p heb -s 2283
bundle exec ruby bin/authz.rb -e -p heb -s 1158
bundle exec ruby bin/authz.rb -e -p heb -s 2246
bundle exec ruby bin/authz.rb -e -p heb -s 2103
bundle exec ruby bin/authz.rb -e -p heb -s 1712
bundle exec ruby bin/authz.rb -e -p heb -s 2367
bundle exec ruby bin/authz.rb -e -p heb -s 2106
bundle exec ruby bin/authz.rb -e -p heb -s 2326
bundle exec ruby bin/authz.rb -e -p heb -s 726
bundle exec ruby bin/authz.rb -e -p heb -s 1096
bundle exec ruby bin/authz.rb -e -p heb -s 2063
bundle exec ruby bin/authz.rb -e -p heb -s 1998
bundle exec ruby bin/authz.rb -e -p heb -s 2011
bundle exec ruby bin/authz.rb -e -p heb -s 1237
bundle exec ruby bin/authz.rb -e -p heb -s 1236
bundle exec ruby bin/authz.rb -e -p heb -s 2270
bundle exec ruby bin/authz.rb -e -p heb -s 2134
bundle exec ruby bin/authz.rb -e -p heb -s 1481
bundle exec ruby bin/authz.rb -e -p heb -s 2112
bundle exec ruby bin/authz.rb -e -p heb -s 2302
bundle exec ruby bin/authz.rb -e -p heb -s 1697
bundle exec ruby bin/authz.rb -e -p heb -s 1082
bundle exec ruby bin/authz.rb -e -p heb -s 2357
bundle exec ruby bin/authz.rb -e -p heb -s 1771
bundle exec ruby bin/authz.rb -e -p heb -s 2339
bundle exec ruby bin/authz.rb -e -p heb -s 1035
bundle exec ruby bin/authz.rb -e -p heb -s 801
bundle exec ruby bin/authz.rb -e -p heb -s 2277
bundle exec ruby bin/authz.rb -e -p heb -s 1627
bundle exec ruby bin/authz.rb -e -p heb -s 2317
bundle exec ruby bin/authz.rb -e -p heb -s 1217
bundle exec ruby bin/authz.rb -e -p heb -s 437
bundle exec ruby bin/authz.rb -e -p heb -s 1438
bundle exec ruby bin/authz.rb -e -p heb -s 1703
bundle exec ruby bin/authz.rb -e -p heb -s 453
bundle exec ruby bin/authz.rb -e -p heb -s 849
bundle exec ruby bin/authz.rb -e -p heb -s 2364
bundle exec ruby bin/authz.rb -e -p heb -s 2341
bundle exec ruby bin/authz.rb -e -p heb -s 1262
bundle exec ruby bin/authz.rb -e -p heb -s 1958
bundle exec ruby bin/authz.rb -e -p heb -s 2284
bundle exec ruby bin/authz.rb -e -p heb -s 2330
bundle exec ruby bin/authz.rb -e -p heb -s 1278
bundle exec ruby bin/authz.rb -e -p heb -s 2130
bundle exec ruby bin/authz.rb -e -p heb -s 638
bundle exec ruby bin/authz.rb -e -p heb -s 2331
bundle exec ruby bin/authz.rb -e -p heb -s 2039
bundle exec ruby bin/authz.rb -e -p heb -s 1530
bundle exec ruby bin/authz.rb -e -p heb -s 1989
bundle exec ruby bin/authz.rb -e -p heb -s 2336
bundle exec ruby bin/authz.rb -e -p heb -s 2150
bundle exec ruby bin/authz.rb -e -p heb -s 2236
bundle exec ruby bin/authz.rb -e -p heb -s 2271
bundle exec ruby bin/authz.rb -e -p heb -s 1080
bundle exec ruby bin/authz.rb -e -p heb -s 693
bundle exec ruby bin/authz.rb -e -p heb -s 814
bundle exec ruby bin/authz.rb -e -p heb -s 1575
bundle exec ruby bin/authz.rb -e -p heb -s 2310
bundle exec ruby bin/authz.rb -e -p heb -s 2335
bundle exec ruby bin/authz.rb -e -p heb -s 2266
bundle exec ruby bin/authz.rb -e -p heb -s 1018
bundle exec ruby bin/authz.rb -e -p heb -s 1432
bundle exec ruby bin/authz.rb -e -p heb -s 2304
bundle exec ruby bin/authz.rb -e -p heb -s 1494
bundle exec ruby bin/authz.rb -e -p heb -s 2354
bundle exec ruby bin/authz.rb -e -p heb -s 2290
bundle exec ruby bin/authz.rb -e -p heb -s 1199
bundle exec ruby bin/authz.rb -e -p heb -s 325
bundle exec ruby bin/authz.rb -e -p heb -s 1566
bundle exec ruby bin/authz.rb -e -p heb -s 328
bundle exec ruby bin/authz.rb -e -p heb -s 932
bundle exec ruby bin/authz.rb -e -p heb -s 945
bundle exec ruby bin/authz.rb -e -p heb -s 2210
bundle exec ruby bin/authz.rb -e -p heb -s 2228
bundle exec ruby bin/authz.rb -e -p heb -s 2215
bundle exec ruby bin/authz.rb -e -p heb -s 1292
bundle exec ruby bin/authz.rb -e -p heb -s 1109
bundle exec ruby bin/authz.rb -e -p heb -s 1659
bundle exec ruby bin/authz.rb -e -p heb -s 1829
bundle exec ruby bin/authz.rb -e -p heb -s 2142
bundle exec ruby bin/authz.rb -e -p heb -s 2066
bundle exec ruby bin/authz.rb -e -p heb -s 614
bundle exec ruby bin/authz.rb -e -p heb -s 2276
bundle exec ruby bin/authz.rb -e -p heb -s 2362
bundle exec ruby bin/authz.rb -e -p heb -s 2128
bundle exec ruby bin/authz.rb -e -p heb -s 2152
bundle exec ruby bin/authz.rb -e -p heb -s 2307
bundle exec ruby bin/authz.rb -e -p heb -s 2356
bundle exec ruby bin/authz.rb -e -p heb -s 2281
bundle exec ruby bin/authz.rb -e -p heb -s 2332
bundle exec ruby bin/authz.rb -e -p heb -s 1672
bundle exec ruby bin/authz.rb -e -p heb -s 1952
bundle exec ruby bin/authz.rb -e -p heb -s 1974
bundle exec ruby bin/authz.rb -e -p heb -s 2360
bundle exec ruby bin/authz.rb -e -p heb -s 2287
bundle exec ruby bin/authz.rb -e -p heb -s 2129
bundle exec ruby bin/authz.rb -e -p heb -s 1046
bundle exec ruby bin/authz.rb -e -p heb -s 2350
bundle exec ruby bin/authz.rb -e -p heb -s 2347
bundle exec ruby bin/authz.rb -e -p heb -s 1701
bundle exec ruby bin/authz.rb -e -p heb -s 1551
bundle exec ruby bin/authz.rb -e -p heb -s 1170
bundle exec ruby bin/authz.rb -e -p heb -s 1696
bundle exec ruby bin/authz.rb -e -p heb -s 2067
bundle exec ruby bin/authz.rb -e -p heb -s 1695
bundle exec ruby bin/authz.rb -e -p heb -s 1489
bundle exec ruby bin/authz.rb -e -p heb -s 1169
bundle exec ruby bin/authz.rb -e -p heb -s 1192
bundle exec ruby bin/authz.rb -e -p heb -s 432
bundle exec ruby bin/authz.rb -e -p heb -s 1172
bundle exec ruby bin/authz.rb -e -p heb -s 2077
bundle exec ruby bin/authz.rb -e -p heb -s 728
bundle exec ruby bin/authz.rb -e -p heb -s 2137
bundle exec ruby bin/authz.rb -e -p heb -s 1848
bundle exec ruby bin/authz.rb -e -p heb -s 1499
bundle exec ruby bin/authz.rb -e -p heb -s 2051
bundle exec ruby bin/authz.rb -e -p heb -s 1752
bundle exec ruby bin/authz.rb -e -p heb -s 2009
bundle exec ruby bin/authz.rb -e -p heb -s 429
bundle exec ruby bin/authz.rb -e -p heb -s 1960
bundle exec ruby bin/authz.rb -e -p heb -s 1959
bundle exec ruby bin/authz.rb -e -p heb -s 1645
bundle exec ruby bin/authz.rb -e -p heb -s 1316
bundle exec ruby bin/authz.rb -e -p heb -s 1676
bundle exec ruby bin/authz.rb -e -p heb -s 388
bundle exec ruby bin/authz.rb -e -p heb -s 2316
bundle exec ruby bin/authz.rb -e -p heb -s 2094
bundle exec ruby bin/authz.rb -e -p heb -s 1776
bundle exec ruby bin/authz.rb -e -p heb -s 909
bundle exec ruby bin/authz.rb -e -p heb -s 222
bundle exec ruby bin/authz.rb -e -p heb -s 1097
bundle exec ruby bin/authz.rb -e -p heb -s 1098
bundle exec ruby bin/authz.rb -e -p heb -s 1099
bundle exec ruby bin/authz.rb -e -p heb -s 2289
bundle exec ruby bin/authz.rb -e -p heb -s 192
bundle exec ruby bin/authz.rb -e -p heb -s 2104
bundle exec ruby bin/authz.rb -e -p heb -s 2229
bundle exec ruby bin/authz.rb -e -p heb -s 2311
bundle exec ruby bin/authz.rb -e -p heb -s 2213
bundle exec ruby bin/authz.rb -e -p heb -s 2342
bundle exec ruby bin/authz.rb -e -p heb -s 724
bundle exec ruby bin/authz.rb -e -p heb -s 958
bundle exec ruby bin/authz.rb -e -p heb -s 2351
bundle exec ruby bin/authz.rb -e -p heb -s 1342
bundle exec ruby bin/authz.rb -e -p heb -s 2247
bundle exec ruby bin/authz.rb -e -p heb -s 2102
bundle exec ruby bin/authz.rb -e -p heb -s 2245
