bundle exec ruby bin/authz.rb -s 189 -p ebc_complete; bundle exec ruby bin/authz.rb -s 189 -p ebc_backlist -e
bundle exec ruby bin/authz.rb -s 269 -p ebc_complete; bundle exec ruby bin/authz.rb -s 269 -p ebc_backlist -e
bundle exec ruby bin/authz.rb -s 398 -p ebc_complete; bundle exec ruby bin/authz.rb -s 398 -p ebc_backlist -e
bundle exec ruby bin/authz.rb -s 406 -p ebc_complete; bundle exec ruby bin/authz.rb -s 406 -p ebc_backlist -e
bundle exec ruby bin/authz.rb -s 516 -p ebc_complete; bundle exec ruby bin/authz.rb -s 516 -p ebc_backlist -e
bundle exec ruby bin/authz.rb -s 700 -p ebc_complete; bundle exec ruby bin/authz.rb -s 700 -p ebc_backlist -e
bundle exec ruby bin/authz.rb -s 825 -p ebc_complete; bundle exec ruby bin/authz.rb -s 825 -p ebc_backlist -e
bundle exec ruby bin/authz.rb -s 879 -p ebc_complete; bundle exec ruby bin/authz.rb -s 879 -p ebc_backlist -e
bundle exec ruby bin/authz.rb -s 900 -p ebc_complete; bundle exec ruby bin/authz.rb -s 900 -p ebc_backlist -e
bundle exec ruby bin/authz.rb -s 1193 -p ebc_complete; bundle exec ruby bin/authz.rb -s 1193 -p ebc_backlist -e
bundle exec ruby bin/authz.rb -s 1306 -p ebc_complete; bundle exec ruby bin/authz.rb -s 1306 -p ebc_backlist -e
bundle exec ruby bin/authz.rb -s 2096 -p ebc_complete; bundle exec ruby bin/authz.rb -s 2096 -p ebc_backlist -e
bundle exec ruby bin/authz.rb -s 676 -p ebc_complete; bundle exec ruby bin/authz.rb -s 676 -p ebc_backlist -e
bundle exec ruby bin/authz.rb -s 1810 -p ebc_complete; bundle exec ruby bin/authz.rb -s 1810 -p ebc_backlist -e
bundle exec ruby bin/authz.rb -s 1984 -p ebc_complete; bundle exec ruby bin/authz.rb -s 1984 -p ebc_backlist -e
bundle exec ruby bin/authz.rb -s 1929 -p ebc_complete; bundle exec ruby bin/authz.rb -s 1929 -p ebc_backlist -e
bundle exec ruby bin/authz.rb -s 100236 -p ebc_complete; bundle exec ruby bin/authz.rb -s 100236 -p ebc_backlist -e
bundle exec ruby bin/authz.rb -s 100235 -p ebc_complete; bundle exec ruby bin/authz.rb -s 100235 -p ebc_backlist -e
bundle exec ruby bin/authz.rb -s 100234 -p ebc_complete; bundle exec ruby bin/authz.rb -s 100234 -p ebc_backlist -e
bundle exec ruby bin/authz.rb -s 100233 -p ebc_complete; bundle exec ruby bin/authz.rb -s 100233 -p ebc_backlist -e
bundle exec ruby bin/authz.rb -s 100232 -p ebc_complete; bundle exec ruby bin/authz.rb -s 100232 -p ebc_backlist -e
bundle exec ruby bin/authz.rb -s 100231 -p ebc_complete; bundle exec ruby bin/authz.rb -s 100231 -p ebc_backlist -e
bundle exec ruby bin/authz.rb -s 100230 -p ebc_complete; bundle exec ruby bin/authz.rb -s 100230 -p ebc_backlist -e
bundle exec ruby bin/authz.rb -s 100229 -p ebc_complete; bundle exec ruby bin/authz.rb -s 100229 -p ebc_backlist -e
bundle exec ruby bin/authz.rb -s 100228 -p ebc_complete; bundle exec ruby bin/authz.rb -s 100228 -p ebc_backlist -e
bundle exec ruby bin/authz.rb -s 100227 -p ebc_complete; bundle exec ruby bin/authz.rb -s 100227 -p ebc_backlist -e
bundle exec ruby bin/authz.rb -s 100226 -p ebc_complete; bundle exec ruby bin/authz.rb -s 100226 -p ebc_backlist -e
bundle exec ruby bin/authz.rb -s 100225 -p ebc_complete; bundle exec ruby bin/authz.rb -s 100225 -p ebc_backlist -e
bundle exec ruby bin/authz.rb -s 100224 -p ebc_complete; bundle exec ruby bin/authz.rb -s 100224 -p ebc_backlist -e
bundle exec ruby bin/authz.rb -s 100223 -p ebc_complete; bundle exec ruby bin/authz.rb -s 100223 -p ebc_backlist -e
bundle exec ruby bin/authz.rb -s 100222 -p ebc_complete; bundle exec ruby bin/authz.rb -s 100222 -p ebc_backlist -e
bundle exec ruby bin/authz.rb -s 100221 -p ebc_complete; bundle exec ruby bin/authz.rb -s 100221 -p ebc_backlist -e
bundle exec ruby bin/authz.rb -s 100220 -p ebc_complete; bundle exec ruby bin/authz.rb -s 100220 -p ebc_backlist -e
bundle exec ruby bin/authz.rb -s 100219 -p ebc_complete; bundle exec ruby bin/authz.rb -s 100219 -p ebc_backlist -e
bundle exec ruby bin/authz.rb -s 100218 -p ebc_complete; bundle exec ruby bin/authz.rb -s 100218 -p ebc_backlist -e
bundle exec ruby bin/authz.rb -s 100217 -p ebc_complete; bundle exec ruby bin/authz.rb -s 100217 -p ebc_backlist -e
bundle exec ruby bin/authz.rb -s 100216 -p ebc_complete; bundle exec ruby bin/authz.rb -s 100216 -p ebc_backlist -e
bundle exec ruby bin/authz.rb -s 100215 -p ebc_complete; bundle exec ruby bin/authz.rb -s 100215 -p ebc_backlist -e
bundle exec ruby bin/authz.rb -s 100214 -p ebc_complete; bundle exec ruby bin/authz.rb -s 100214 -p ebc_backlist -e
bundle exec ruby bin/authz.rb -s 100213 -p ebc_complete; bundle exec ruby bin/authz.rb -s 100213 -p ebc_backlist -e
bundle exec ruby bin/authz.rb -s 100212 -p ebc_complete; bundle exec ruby bin/authz.rb -s 100212 -p ebc_backlist -e
bundle exec ruby bin/authz.rb -s 100211 -p ebc_complete; bundle exec ruby bin/authz.rb -s 100211 -p ebc_backlist -e
bundle exec ruby bin/authz.rb -s 100210 -p ebc_complete; bundle exec ruby bin/authz.rb -s 100210 -p ebc_backlist -e
bundle exec ruby bin/authz.rb -s 100209 -p ebc_complete; bundle exec ruby bin/authz.rb -s 100209 -p ebc_backlist -e
bundle exec ruby bin/authz.rb -s 100208 -p ebc_complete; bundle exec ruby bin/authz.rb -s 100208 -p ebc_backlist -e
bundle exec ruby bin/authz.rb -s 100245 -p ebc_complete; bundle exec ruby bin/authz.rb -s 100245 -p ebc_backlist -e